### ISSUE TITLE
Real time charts not working

### ISSUE THREAD

**Issue by chandanch** [fusioncharts/angular4-fusioncharts#11]
When we try to use the **realtimeline** chart the chart throws message as "_Chart not supported_".

Please refer to this plunk: https://plnkr.co/edit/84dEEJ6sbBHr4n8Ft2XB?p=preview 

In this plunk we have added two data points by default. It works in the plain JS version but does not work in the Angular 4 version.

Refer to this fiddle for plain js version:
https://jsfiddle.net/chandan_ch/79f81dug/2/ 

On the browser console we get the following error:
`
Failed to load resource: the server responded with a status of 404 ()
run.plnkr.co/NOgIETInay1xPNbY/fusioncharts.widgets.js
`
How do we add widgets in NgModule?

Also there is no documentation & example for real-time charts please add the documentation and an example as well.

**Comment by rousan** [comment]
Hi @chandanch 
You need to import `widgets` module for real-time charts in your `app.module.ts` file as follows:

```typescript
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import * as FusionCharts from 'fusioncharts';
import * as Charts from 'fusioncharts/fusioncharts.charts';
// Here import Widgets module
import * as Widgets from 'fusioncharts/fusioncharts.widgets';
import * as FintTheme from 'fusioncharts/themes/fusioncharts.theme.fint';
import * as OceanTheme from 'fusioncharts/themes/fusioncharts.theme.ocean';
import { FusionChartsModule } from 'angular4-fusioncharts';
import { AppComponent } from './app.component';

// Here pass Widgets module to resolve
FusionChartsModule.fcRoot(FusionCharts, Charts, Widgets, FintTheme, OceanTheme)

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        FusionChartsModule
    ],
    providers: [],
    bootstrap: [ AppComponent ]
})
export class AppModule { }

```

The modified plunkr [link](https://plnkr.co/edit/15EBUZr38PQ7yTvfc3Zx?p=preview).
