### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by xnyssxy** [fusioncharts/angular4-fusioncharts#13]
follow the [official Demo link](https://fusioncharts.github.io/angular4-fusioncharts/) when run the demos, i get the error:
Error: (SystemJS) Error: XHR error (404) loading https://fusioncharts.github.io/angular4-fusioncharts/samples/change-chart-type-runtime/angular4-fc/build/rxjs-compat/Observable at XMLHttpRequest.wrapFn (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1188:39) at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:421:31) at Zone.runTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:188:47) at ZoneTask.invokeTask [as invoke] (https://unpkg.com/zone.js@0.8.26/dist/zone.js:496:34) at invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1540:14) at XMLHttpRequest.globalZoneAwareCallback (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1566:17) Error loading https://fusioncharts.github.io/angular4-fusioncharts/samples/change-chart-type-runtime/angular4-fc/build/rxjs-compat/Observable as "rxjs-compat/Observable" from https://unpkg.com/rxjs/Observable.js

Could you please fix it?
Thank you 😃

**Comment by rousan** [comment]
Hey @xnyssxy 
Thank you very much for reporting this issue. I fixed it, please clear your browser cache before visiting the site.
