### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by alereisan** [fusioncharts/angular4-fusioncharts#14]
The demos at https://fusioncharts.github.io/angular4-fusioncharts/ are not working:

> Error: (SystemJS) Error: XHR error (404) loading https://unpkg.com/Subject at XMLHttpRequest.wrapFn (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1188:39) at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:421:31) at Zone.runTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:188:47) at ZoneTask.invokeTask [as invoke] (https://unpkg.com/zone.js@0.8.26/dist/zone.js:496:34) at invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1540:14) at XMLHttpRequest.globalZoneAwareCallback (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1566:17) Error loading https://unpkg.com/Subject as "./Subject" from https://unpkg.com/rxjs@5.5.10

**Comment by rousan** [comment]
@alereisan 
Thanks for reporting this issue. Now it is fixed, please clear your browser cache if not working.
