### ISSUE TITLE
if we have a licensed version , how we add license in package.json when installing the package with npm install angular4-fusioncharts --save

### ISSUE THREAD

**Issue by chinthu** [fusioncharts/angular4-fusioncharts#2]

**Comment by rousan** [comment]
Hello @chinthu

If you have licensed version of `FusionCharts`, then you don't need to add any license information in your `package.json` file.
Please follow the below steps to use your licensed version of `FusionCharts`:

1. Create a folder named `fusioncharts` in your project root or elsewhere and copy the library module files of your licensed version of `FusionCharts` into that folder.

1.  Install the `angular4-fusioncharts` wrapper:

```bash
npm install angular4-fusioncharts --save
```
2. After installing `angular4-fusioncharts`, import it in your Angular `AppModule` as follows:

```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FusionChartsModule } from 'angular4-fusioncharts';

 // import your licensed version of fusioncharts
import * as FusionCharts from './fusioncharts';
import * as Charts from './fusioncharts/fusioncharts.charts';
import * as FintTheme from './fusioncharts/themes/fusioncharts.theme.fint';

import { AppComponent } from './app.component';

FusionChartsModule.fcRoot(FusionCharts, Charts, FintTheme);

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        FusionChartsModule
    ],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule { }
```
3. Once the library is imported, you can use this component in your Angular application:

In your Angular `AppComponent`:

```javascript
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent {
    id = 'chart1';
    width = 600;
    height = 400;
    type = 'column2d';
    dataFormat = 'json';
    dataSource;
    title = 'Angular4 FusionCharts Sample';

    constructor() {
        this.dataSource = {
            "chart": {
                "caption": "Harry's SuperMart",
                "subCaption": "Top 5 stores in last month by revenue",
                "numberprefix": "$",
                "theme": "fint"
            },
            "data": [
                {
                    "label": "Bakersfield Central",
                    "value": "880000"
                },
                {
                    "label": "Garden Groove harbour",
                    "value": "730000"
                },
                {
                    "label": "Los Angeles Topanga",
                    "value": "590000"
                },
                {
                    "label": "Compton-Rancho Dom",
                    "value": "520000"
                },
                {
                    "label": "Daly City Serramonte",
                    "value": "330000"
                }
            ]
        }
    }
}
```

4. Now, You can use `<fusioncharts>` component in your `app.component.html` template:

```html
<h1>
  {{title}}
</h1>
<fusioncharts
    [width]="width"
    [height]="height"
    [type]="type"
    [dataFormat]="dataFormat"
    [dataSource]="dataSource"
></fusioncharts>
```

Let us know if you face any problem.

**Comment by tosehee75** [comment]
You need to add "useJs": true as well. Otherwise, this doesn't work

**Comment by nikunjgajera** [comment]
Hi @rousan 
I tried your solutions but i got below error

ERROR in : Cannot find module './fusioncharts/fusioncharts'.
ERROR in : Cannot find module './fusioncharts/fusioncharts.charts'.
ERROR in : Cannot find module './fusioncharts/themes/fusioncharts.theme.fint'.

Have you any idea about this error?

**Comment by hitesh-adabala** [comment]
> Hi @rousan
> I tried your solutions but i got below error
> 
> ERROR in : Cannot find module './fusioncharts/fusioncharts'.
> ERROR in : Cannot find module './fusioncharts/fusioncharts.charts'.
> ERROR in : Cannot find module './fusioncharts/themes/fusioncharts.theme.fint'.
> 
> Have you any idea about this error?
even i am facing the same now. please let me know how to solve this.

**Comment by ashok1994** [comment]
Hi, @hitesh-adabala  , We request you to use our updated version of angular-fusioncharts https://github.com/fusioncharts/angular-fusioncharts ,you can install it by using `npm install angular-fusioncharts@latest`
