### ISSUE TITLE
While migrating abgular 2 rc4 to angular 6 I am facing this error:- Cannot find module 'webpack/lib/removeAndDo' please help me out.

### ISSUE THREAD

**Issue by Nisha-Yadav-1** [fusioncharts/angular4-fusioncharts#21]

**Comment by ashok1994** [comment]
@Nisha-Yadav-1  Please refer [angular-fusioncharts](https://github.com/fusioncharts/angular-fusioncharts/) which support angular2 and above, Upgrade process is simple, just replace `angular4-fusioncharts` with `angular-fusioncharts` and refer docs for additional details.
Please let me know if it works out for you.

**Comment by ashok1994** [comment]
Closing for now
