### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by pumulo** [fusioncharts/angular4-fusioncharts#3]
I am attempting to use this with Angular 5. When I try:
import * as FusionCharts from 'fusioncharts';
import * as Charts from 'fusioncharts/fusioncharts.charts';
import * as FintTheme from 'fusioncharts/themes/fusioncharts.theme.fint';
I am not able to find the modules. Is there an update for supporting Angular 5?

**Comment by rousan** [comment]
Hi @pumulo,
You need to install `FusionCharts` library before importing it.

Run the following commands:
```bash
npm install fusioncharts --save
npm install angular4-fusioncharts --save
```

**Comment by pumulo** [comment]
Thank you.
