### ISSUE TITLE
bug with titles

### ISSUE THREAD

**Issue by GoHaddi** [fusioncharts/angular4-fusioncharts#4]
![image](https://user-images.githubusercontent.com/31385201/36061345-9f2b0bbc-0e61-11e8-8d3d-55fc5e96e33c.png)

Hi! When I use the graph, the titles appear very far from the dot itself, when I try to move the mouse towards the dot, the title disappears... Please fix

**Comment by ayanbhaduryfc** [comment]
Hi,

Please share us a sample replicating the issue so that we could assist you further.

For reference please check this sample - https://plnkr.co/edit/p7pGTx2qMBpP5nBBUsBt?p=preview

**Comment by ashok1994** [comment]
Please refer [angular-fusioncharts](https://github.com/fusioncharts/angular-fusioncharts/) for latest documentation.
